{{- if .Values.cassandra.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra1
  namespace: "{{ .Values.infrastructure.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cassandra1
    spec:
      containers:
      - image: "{{ .Values.infrastructure.image }}"
        name: cassandra1
        resources:
          requests:
            memory: "3500Mi"
            cpu: "750m"
          limits:
            memory: "4096Mi"
            cpu: "1000m"
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "{{ .Values.infrastructure.cluster }}"
        - name: CASSANDRA_DC
          value: "{{ .Values.infrastructure.datacenter }}"
        - name: CASSANDRA_RACK
          value: "cr1a"
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: "{{ .Values.infrastructure.endpoint_snitch }}"
        - name: CASSANDRA_BROADCAST_ADDRESS
          value: "cassandra1-external"
        - name: CASSANDRA_RPC_ADDRESS
          value: "{{ .Values.cassandra.rpcAddress }}"
        - name: CASSANDRA_START_RPC
          value:  "{{ .Values.cassandra.startRpc }}"
        - name: CASSANDRA_SEEDS
          value: "{{ .Values.cassandra.seeds }}"
        - name: MAX_HEAP_SIZE
          value: "{{ .Values.cassandra.heapSize }}"
        - name: HEAP_NEWSIZE
          value: "512M"
        ports:
        - containerPort: 7000 # intra-node communication
          name: intranode
        - containerPort: 7001 # TLS intra-node communication
          name: intratls
        - containerPort: 7199 # JMX
          name: jmxport
        - containerPort: 9042 # CQL
          name: cql
        - containerPort: 9160 # thrift service
          name: thrift
        readinessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: {{ .Values.cassandra.failureThreshold }}
        livenessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 15
          failureThreshold: {{ .Values.cassandra.failureThreshold }}
          periodSeconds: 15
        volumeMounts:
        - name: "cassandra1-volume"
          mountPath: /var/lib/cassandra
      volumes:
      - name: "cassandra1-volume"
        persistentVolumeClaim:
          claimName: "cassandra1-persistent-storage"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "cassandra1-persistent-storage"
  namespace: "{{ .Values.infrastructure.namespace }}"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "{{ .Values.infrastructure.storageClass }}"
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: "cassandra1-external"
  namespace: "{{ .Values.infrastructure.namespace }}"
spec:
  type: "LoadBalancer"
  ports:
  - port: 7000
    protocol: TCP
    name: intranode
  - port: 7001
    protocol: TCP
    name: tlsintra
  - port: 7199
    protocol: TCP
    name: jmx
  - port: 9042
    protocol: TCP
    name: cql
  - port: 9160
    protocol: TCP
    name: thrift
  selector:
    app: cassandra1
---
apiVersion: v1
kind: Service
metadata:
  name: "cassandra1-internal"
  namespace: "{{ .Values.infrastructure.namespace }}"
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: "LoadBalancer"
  ports:
  - port: 7000
    protocol: TCP
    name: intranode
  - port: 7001
    protocol: TCP
    name: tlsintra
  - port: 7199
    protocol: TCP
    name: jmx
  - port: 9042
    protocol: TCP
    name: cql
  - port: 9160
    protocol: TCP
    name: thrift
  selector:
    app: cassandra1

{{- end }}
