
replicaCount: 1

application:
  labelValue: postgres

# How to Install/Uninstall
# helm upgrade --install postgres116 ./Postgres11.6
# helm uninstall postgres116
infrastructure:
  namespace: postgres116
  appName: postgres
  username: postgres
  password: "IzzyAcademy2013"
  dataVolume: "/var/lib/postgresql"
  dataPath: "/var/lib/postgresql/data"

image:
  name: postgres
  pullPolicy: IfNotPresent
  tag: "11.6"

service:
  type: LoadBalancer
  port: 5432
  protocol: TCP

resources:
  limits:
     cpu: 1000m
     memory: 4096Mi
  requests:
     cpu: 750m
     memory: 2048Mi
  volume:
    size: 5Gi
    storageClass: managed-premium